/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProcessPoRouteImport } from './routes/api/process-po'
import { Route as ApiAiSearchRouteImport } from './routes/api/ai-search'
import { Route as AuthenticatedSystemRouteImport } from './routes/_authenticated/system'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedOperationsRouteImport } from './routes/_authenticated/operations'
import { Route as AuthenticatedIpMovementsRouteImport } from './routes/_authenticated/ip-movements'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedFulfillmentRouteImport } from './routes/_authenticated/fulfillment'
import { Route as AuthenticatedFpStockRouteImport } from './routes/_authenticated/fp-stock'
import { Route as AuthenticatedFpMovementsRouteImport } from './routes/_authenticated/fp-movements'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedAccountingRouteImport } from './routes/_authenticated/Accounting'
import { Route as ApiPublicSeedUsersRouteImport } from './routes/api/public/seed-users'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessPoRoute = ApiProcessPoRouteImport.update({
  id: '/api/process-po',
  path: '/api/process-po',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSearchRoute = ApiAiSearchRouteImport.update({
  id: '/api/ai-search',
  path: '/api/ai-search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSystemRoute = AuthenticatedSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperationsRoute = AuthenticatedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIpMovementsRoute =
  AuthenticatedIpMovementsRouteImport.update({
    id: '/ip-movements',
    path: '/ip-movements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFulfillmentRoute =
  AuthenticatedFulfillmentRouteImport.update({
    id: '/fulfillment',
    path: '/fulfillment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFpStockRoute = AuthenticatedFpStockRouteImport.update({
  id: '/fp-stock',
  path: '/fp-stock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFpMovementsRoute =
  AuthenticatedFpMovementsRouteImport.update({
    id: '/fp-movements',
    path: '/fp-movements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountingRoute = AuthenticatedAccountingRouteImport.update({
  id: '/Accounting',
  path: '/Accounting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSeedUsersRoute = ApiPublicSeedUsersRouteImport.update({
  id: '/api/public/seed-users',
  path: '/api/public/seed-users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/Accounting': typeof AuthenticatedAccountingRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/fp-movements': typeof AuthenticatedFpMovementsRoute
  '/fp-stock': typeof AuthenticatedFpStockRoute
  '/fulfillment': typeof AuthenticatedFulfillmentRoute
  '/home': typeof AuthenticatedHomeRoute
  '/ip-movements': typeof AuthenticatedIpMovementsRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/system': typeof AuthenticatedSystemRoute
  '/api/ai-search': typeof ApiAiSearchRoute
  '/api/process-po': typeof ApiProcessPoRoute
  '/api/public/seed-users': typeof ApiPublicSeedUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/Accounting': typeof AuthenticatedAccountingRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/fp-movements': typeof AuthenticatedFpMovementsRoute
  '/fp-stock': typeof AuthenticatedFpStockRoute
  '/fulfillment': typeof AuthenticatedFulfillmentRoute
  '/home': typeof AuthenticatedHomeRoute
  '/ip-movements': typeof AuthenticatedIpMovementsRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/system': typeof AuthenticatedSystemRoute
  '/api/ai-search': typeof ApiAiSearchRoute
  '/api/process-po': typeof ApiProcessPoRoute
  '/api/public/seed-users': typeof ApiPublicSeedUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/Accounting': typeof AuthenticatedAccountingRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/fp-movements': typeof AuthenticatedFpMovementsRoute
  '/_authenticated/fp-stock': typeof AuthenticatedFpStockRoute
  '/_authenticated/fulfillment': typeof AuthenticatedFulfillmentRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/ip-movements': typeof AuthenticatedIpMovementsRoute
  '/_authenticated/operations': typeof AuthenticatedOperationsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/system': typeof AuthenticatedSystemRoute
  '/api/ai-search': typeof ApiAiSearchRoute
  '/api/process-po': typeof ApiProcessPoRoute
  '/api/public/seed-users': typeof ApiPublicSeedUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/Accounting'
    | '/finance'
    | '/fp-movements'
    | '/fp-stock'
    | '/fulfillment'
    | '/home'
    | '/ip-movements'
    | '/operations'
    | '/sales'
    | '/system'
    | '/api/ai-search'
    | '/api/process-po'
    | '/api/public/seed-users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/Accounting'
    | '/finance'
    | '/fp-movements'
    | '/fp-stock'
    | '/fulfillment'
    | '/home'
    | '/ip-movements'
    | '/operations'
    | '/sales'
    | '/system'
    | '/api/ai-search'
    | '/api/process-po'
    | '/api/public/seed-users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/Accounting'
    | '/_authenticated/finance'
    | '/_authenticated/fp-movements'
    | '/_authenticated/fp-stock'
    | '/_authenticated/fulfillment'
    | '/_authenticated/home'
    | '/_authenticated/ip-movements'
    | '/_authenticated/operations'
    | '/_authenticated/sales'
    | '/_authenticated/system'
    | '/api/ai-search'
    | '/api/process-po'
    | '/api/public/seed-users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAiSearchRoute: typeof ApiAiSearchRoute
  ApiProcessPoRoute: typeof ApiProcessPoRoute
  ApiPublicSeedUsersRoute: typeof ApiPublicSeedUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/process-po': {
      id: '/api/process-po'
      path: '/api/process-po'
      fullPath: '/api/process-po'
      preLoaderRoute: typeof ApiProcessPoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-search': {
      id: '/api/ai-search'
      path: '/api/ai-search'
      fullPath: '/api/ai-search'
      preLoaderRoute: typeof ApiAiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/system': {
      id: '/_authenticated/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AuthenticatedSystemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations': {
      id: '/_authenticated/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthenticatedOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ip-movements': {
      id: '/_authenticated/ip-movements'
      path: '/ip-movements'
      fullPath: '/ip-movements'
      preLoaderRoute: typeof AuthenticatedIpMovementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fulfillment': {
      id: '/_authenticated/fulfillment'
      path: '/fulfillment'
      fullPath: '/fulfillment'
      preLoaderRoute: typeof AuthenticatedFulfillmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fp-stock': {
      id: '/_authenticated/fp-stock'
      path: '/fp-stock'
      fullPath: '/fp-stock'
      preLoaderRoute: typeof AuthenticatedFpStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fp-movements': {
      id: '/_authenticated/fp-movements'
      path: '/fp-movements'
      fullPath: '/fp-movements'
      preLoaderRoute: typeof AuthenticatedFpMovementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/Accounting': {
      id: '/_authenticated/Accounting'
      path: '/Accounting'
      fullPath: '/Accounting'
      preLoaderRoute: typeof AuthenticatedAccountingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/seed-users': {
      id: '/api/public/seed-users'
      path: '/api/public/seed-users'
      fullPath: '/api/public/seed-users'
      preLoaderRoute: typeof ApiPublicSeedUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountingRoute: typeof AuthenticatedAccountingRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedFpMovementsRoute: typeof AuthenticatedFpMovementsRoute
  AuthenticatedFpStockRoute: typeof AuthenticatedFpStockRoute
  AuthenticatedFulfillmentRoute: typeof AuthenticatedFulfillmentRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedIpMovementsRoute: typeof AuthenticatedIpMovementsRoute
  AuthenticatedOperationsRoute: typeof AuthenticatedOperationsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSystemRoute: typeof AuthenticatedSystemRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountingRoute: AuthenticatedAccountingRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedFpMovementsRoute: AuthenticatedFpMovementsRoute,
  AuthenticatedFpStockRoute: AuthenticatedFpStockRoute,
  AuthenticatedFulfillmentRoute: AuthenticatedFulfillmentRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedIpMovementsRoute: AuthenticatedIpMovementsRoute,
  AuthenticatedOperationsRoute: AuthenticatedOperationsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSystemRoute: AuthenticatedSystemRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAiSearchRoute: ApiAiSearchRoute,
  ApiProcessPoRoute: ApiProcessPoRoute,
  ApiPublicSeedUsersRoute: ApiPublicSeedUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
